############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "writeup/"
weight = 2

[[main]]
name = "Code"
url = "code/"
weight = 3